{% set name = "slurmio" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/slurmio-{{ version }}.tar.gz
  sha256: 525bbfdd2960733f6bd2b60e3ce719edaa79b10dfc264dce14fd6d140753e308

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - slurmio
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamltyson/slurmio
  summary: Python tools to interface with slurm
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
