{% set name = "slurmio" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/slurmio-{{ version }}.tar.gz
  sha256: 24bb87f08da0ca2d5e466204af37f4df3d869009cf012af28246b9dcb4cd380a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - slurmio
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamltyson/slurmio
  summary: Python tools to interface with slurm
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
